name: "🐦Submit a Tweet Proposal"
description: "Propose tweets for @Zenon_Network feed."
title: "[Enter Short Description]"
labels: ["tweet"]
assignees: []

body:
  - type: checkboxes
    id: discussion-check
    attributes:
      label: "Is there a Discussion for this tweet?"
      description: "Please [submit a discussion](https://github.com/coinselor/twitter/discussions) for this tweet before submitting this tweet proposal."
      options:
        - label: "There is an existing discussion for this tweet."
          required: true

  - type: input
    id: discussion-link
    attributes:
      label: "Link to Discussion of Tweet Content"
      description: "Provide a link to the GitHub Discussion related to this tweet."
      placeholder: "https://github.com/coinselor/twitter/discussions/321"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Tweet Information\nFill out the details below for your tweet proposal."

  - type: dropdown
    id: tweet-date
    attributes:
      label: "When to tweet?"
      description: "ASAP or Scheduled?"
      options:
        - "As soon as possible"
        - "Scheduled (Specify Date Below)"
    validations:
      required: true

  - type: input
    id: scheduled-date
    attributes:
      label: "Scheduled Date"
      description: "If scheduled, specify the date (YYYY-MM-DD). Leave blank if not applicable."
      placeholder: "YYYY-MM-DD"
    validations:
      required: false

  - type: textarea
    id: tweet-content
    attributes:
      label: "Content of the Tweet"
      description: "Write the primary content of the tweet here. Make sure it is less than 280 characters. [Try it out](https://twitter.com/compose/tweet)."
      placeholder: "Enter tweet content"
    validations:
      required: true

  - type: checkboxes
    id: create-thread
    attributes:
      label: "Add a reply / Create a thread"
      description: "Check this if the plan is to create a thread."
      options:
        - label: "Yes, I want to add another tweet as a reply."

  - type: textarea
    id: additional-tweet-content
    attributes:
      label: "Additional Tweet Content"
      description: "Write the content of your additional tweet for the thread here. (Optional) For multiple replies, separate each tweet with a line break including the characters '---'. Example: This is the first reply --- This is the second reply"
      placeholder: "Enter additional tweet content"
    validations:
      required: false

  - type: checkboxes
    id: tweet-media
    attributes:
      label: "Does the tweet include media?"
      description: "Check if there will be media or an image with the tweet."
      options:
        - label: "Yes"

  - type: textarea
    id: add-media
    attributes:
      label: "Add media as an attachment"
      description: "Click the paper clip icon (📎) to add a file"
      placeholder: "📎"
    validations:
      required: false
